import { Providers } from "@/app/providers";
import type { Metadata } from "next";
import { Manrope, Michroma, Space_Grotesk, Zen_Dots } from "next/font/google";

const michroma = Michroma({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

const zenDots = Zen_Dots({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  display: "swap",
});

const manrope = Manrope({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Crazy Labs - Enter the Laboratory",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${michroma.className} ${zenDots.className} ${spaceGrotesk.className} ${manrope.className}`}>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
